# Generated by Django 5.2.6 on 2025-10-25 06:25

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_classroom_students_alter_course_instructor'),
        ('users', '0002_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profiles/default.jpg', upload_to=users.models.user_profile_upload_path)),
                ('bio', models.TextField(blank=True, null=True)),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='enrolled_users', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
