# Generated by Django 5.2.6 on 2025-11-09 10:01

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profiles/images/default-avatar.png', upload_to=users.models.user_profile_upload_path),
        ),
    ]
