# Generated by Django 5.0.6 on 2026-02-04 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('book_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('both', 'Digital & Physical')], default='digital', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, help_text='Cover image of the book', null=True, upload_to='books/covers/')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/files/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of physical books in stock')),
                ('min_stock_alert', models.PositiveIntegerField(default=5, help_text='Alert when stock goes below this number')),
                ('shipping_available', models.BooleanField(default=True, help_text='Is mailing enabled?')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Book Categories',
                'ordering': ['name'],
            },
        ),
    ]
