# Generated by Django 5.2.6 on 2025-10-03 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('book_type', models.CharField(choices=[('digital', 'Digital'), ('physical', 'Physical'), ('both', 'Digital & Physical')], default='digital', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Number of physical books in stock')),
                ('shipping_available', models.BooleanField(default=True, help_text='Is mailing enabled?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
