# Generated by Django 5.0.6 on 2026-02-04 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('letter_grades', models.JSONField(default=list, help_text='Format: [{"letter": "A", "min": 18, "max": 20}, ...]')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer'), ('winter', 'Winter')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('total_grades', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_finalized', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'ordering': ['-year', '-term'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Score')),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Maximum Score')),
                ('grade_type', models.CharField(choices=[('assignment', 'Assignment/Homework'), ('quiz', 'Quiz'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('sessional', 'Sessional/Classwork'), ('participation', 'Participation'), ('project', 'Project')], max_length=20, verbose_name='Grade Type')),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in GPA calculation (e.g., 1.0 for normal, 2.0 for important)', max_digits=4)),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Graded At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published to Student')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='courses.assignment', verbose_name='Related Assignment')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course', verbose_name='Course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='exams.exam', verbose_name='Related Exam')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['-created_at'],
            },
        ),
    ]
