# Generated by Django 5.0.6 on 2026-02-04 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['instructor', 'employee', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_grades', to=settings.AUTH_USER_MODEL, verbose_name='Graded By'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards', to='courses.classroom'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='courses.course'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(('score__lte', models.F('max_score'))), name='score_lte_max_score'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'assignment'), ('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'course', 'term', 'year')},
        ),
    ]
