# Generated by Django 5.2.6 on 2025-12-01 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_submission_grade_remove_submission_graded_at_and_more'),
        ('exams', '0004_alter_question_options_remove_question_order'),
        ('grades', '0002_rename_grades_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('letter_grades', models.JSONField(default=list, help_text='Format: [{"letter": "A", "min": 18, "max": 20}, ...]')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer'), ('winter', 'Winter')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('total_grades', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_finalized', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Card',
                'verbose_name_plural': 'Report Cards',
                'ordering': ['-year', '-term'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='grade',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Graded At'),
        ),
        migrations.AddField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['instructor', 'employee', 'manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_grades', to=settings.AUTH_USER_MODEL, verbose_name='Graded By'),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published to Student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in GPA calculation (e.g., 1.0 for normal, 2.0 for important)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='courses.assignment', verbose_name='Related Assignment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_entries', to='exams.exam', verbose_name='Related Exam'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('assignment', 'Assignment/Homework'), ('quiz', 'Quiz'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('sessional', 'Sessional/Classwork'), ('participation', 'Participation'), ('project', 'Project')], max_length=20, verbose_name='Grade Type'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6, verbose_name='Maximum Score'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'assignment'), ('student', 'exam')},
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', models.F('max_score'))), name='score_lte_max_score'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards', to='courses.classroom'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='courses.course'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'course', 'term', 'year')},
        ),
    ]
