# Generated by Django 5.2.6 on 2025-11-01 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_classroom_students_alter_course_instructor'),
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.PositiveIntegerField(default=0, help_text='Total marks for the exam (auto-calculated or set manually)'),
        ),
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_media/audio/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='exam_media/images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('essay', 'Essay / Open Response'), ('audio_mcq', 'Listening (Audio) + MCQ'), ('audio_essay', 'Listening (Audio) + Essay'), ('image_mcq', 'Image + MCQ'), ('image_essay', 'Image + Essay')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='text_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='exam_responses/'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.choice'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('student', 'exam')},
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('student', 'question')},
        ),
    ]
