# Generated by Django 5.2.6 on 2025-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
