# Generated by Django 5.2.6 on 2025-11-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examresult_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
