# Generated by Django 5.2.6 on 2025-12-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_classroom_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='graded_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='graded_by',
        ),
    ]
